annotations:
  # --- Provenance Metadata ---
  repackage.provenance/repackaged-by: "mirrorctl dev"
  repackage.provenance/original-chart-url: "https://grafana.github.io/helm-charts"
  repackage.provenance/original-chart-name: "grafana"
  repackage.provenance/original-chart-version: "7.0.19"
  repackage.provenance/timestamp: "2025-11-14T16:42:39Z"
  artifacthub.io/license: AGPL-3.0-only
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/grafana/helm-charts
    - name: Upstream Project
      url: https://github.com/grafana/grafana
apiVersion: v2
appVersion: 10.2.2
description: The leading tool for querying and visualizing time series and metrics.
home: https://grafana.com
icon: https://artifacthub.io/image/b4fed1a7-6c8f-4945-b99d-096efa3e4116
keywords:
- monitoring
- metric
kubeVersion: ^1.8.0-0
maintainers:
- email: zanhsieh@gmail.com
  name: zanhsieh
- email: rluckie@cisco.com
  name: rtluckie
- email: maor.friedman@redhat.com
  name: maorfr
- email: miroslav.hadzhiev@gmail.com
  name: Xtigyro
- email: mail@torstenwalter.de
  name: torstenwalter
name: grafana
sources:
- https://github.com/grafana/grafana
- https://github.com/grafana/helm-charts
type: application
version: 7.0.19-poc
