annotations:
  # --- Provenance Metadata ---
  repackage.provenance/repackaged-by: "mirrorctl dev"
  repackage.provenance/original-chart-url: "https://charts.bitnami.com/bitnami"
  repackage.provenance/original-chart-name: "common"
  repackage.provenance/original-chart-version: "2.14.1"
  repackage.provenance/timestamp: "2025-11-14T16:26:31Z"
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
appVersion: 2.14.1
description: A Library Helm Chart for grouping common logic between bitnami charts.
  This chart is not deployable by itself.
home: https://bitnami.com
icon: https://bitnami.com/downloads/logos/bitnami-mark.png
keywords:
- common
- helper
- template
- function
- bitnami
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: common
sources:
- https://github.com/bitnami/charts
type: library
version: 2.14.1-poc
