name: Release the binaries

on:
  release:
    types: [created]
  push:
    tags:
      - 'v*'

permissions:
  contents: write
#  id-token: write
#  attestations: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true

      - name: Install syft
        uses: anchore/sbom-action/download-syft@v0

      - uses: sigstore/cosign-installer@main
        with:
          cosign-release: "v3.0.2"

      - name: Prepare cosign key
        run: |
          echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
          chmod 600 cosign.key

      - name: Run GoReleaser - Build binaries and generates a GH release
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_PWD: ${{ secrets.COSIGN_PWD }}

#      # After GoReleaser runs, attest all the files in ./dist/checksums.txt:
#      - uses: actions/attest-build-provenance@v3
#        with:
#          subject-checksums: ./dist/checksums.txt
#      # After GoReleaser runs, attest all the images in ./dist/digests.txt:
#      - uses: actions/attest-build-provenance@v3
#        if: startsWith(github.ref, 'refs/tags/v') # snapshots won't push docker images
#        with:
#          subject-checksums: ./dist/digests.txt
